---
version: '3.3'

services:
  drupal:
    container_name: drupal
    build:
      context: ./
      dockerfile: Dockerfile-test
    ports:
      - 80:80
    restart: always

  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    restart: always


